/*
 * THIS FILE WAS AUTOGENERATED BY THE DIGITAL ASSET Daml SCALA CODE GENERATOR
 * DO NOT EDIT BY HAND!
 */
import _root_.com.daml.ledger.client.{binding=>$u0020lfdomainapi}
package co.topl.daml.models {
  object EventDecoder extends ` lfdomainapi`.EventDecoderApi(templateTypes = _root_.scala.collection.immutable.Seq[(` lfdomainapi`.TemplateCompanion[_$1] forSome { 
    type _$1
  })](co.topl.daml.models.Topl.Asset, co.topl.daml.models.Topl.User))
}
