/*
 * THIS FILE WAS AUTOGENERATED BY THE DIGITAL ASSET Daml SCALA CODE GENERATOR
 * DO NOT EDIT BY HAND!
 */
package co.topl.daml.models {
  private[models] object `Package IDs` {
    val `DA.Date.Types`: _root_.scala.Predef.String = "bfcd37bd6b84768e86e432f5f6c33e25d9e7724a9d42e33875ff74f6348e733f";
    val `DA.Exception.ArithmeticError`: _root_.scala.Predef.String = "cb0552debf219cc909f51cbb5c3b41e9981d39f8f645b1f35e2ef5be2e0b858a";
    val `DA.Exception.AssertionFailed`: _root_.scala.Predef.String = "3f4deaf145a15cdcfa762c058005e2edb9baa75bb7f95a4f8f6f937378e86415";
    val `DA.Exception.GeneralError`: _root_.scala.Predef.String = "86828b9843465f419db1ef8a8ee741d1eef645df02375ebf509cdc8c3ddd16cb";
    val `DA.Exception.PreconditionFailed`: _root_.scala.Predef.String = "f20de1e4e37b92280264c08bf15eca0be0bc5babd7a7b5e574997f154c00cb78";
    val `DA.Generics`: _root_.scala.Predef.String = "9de3ae0b7b4e753f7ce2a5dcaa8d49ab4b92c4d8a8fb9589b5f8c893fbea5bd1";
    val `DA.Internal.Down`: _root_.scala.Predef.String = "057eed1fd48c238491b8ea06b9b5bf85a5d4c9275dd3f6183e0e6b01730cc2ba";
    val `DA.Internal.Template`: _root_.scala.Predef.String = "d14e08374fc7197d6a0de468c968ae8ba3aadbf9315476fd39071831f5923662";
    val `DA.Logic.Types`: _root_.scala.Predef.String = "c1f1f00558799eec139fb4f4c76f95fb52fa1837a5dd29600baa1c8ed1bdccfd";
    val `DA.Monoid.Types`: _root_.scala.Predef.String = "6c2c0667393c5f92f1885163068cd31800d2264eb088eb6fc740e11241b2bf06";
    val `DA.Next.Map`: _root_.scala.Predef.String = "9de3ae0b7b4e753f7ce2a5dcaa8d49ab4b92c4d8a8fb9589b5f8c893fbea5bd1";
    val `DA.Next.Set`: _root_.scala.Predef.String = "9de3ae0b7b4e753f7ce2a5dcaa8d49ab4b92c4d8a8fb9589b5f8c893fbea5bd1";
    val `DA.NonEmpty.Types`: _root_.scala.Predef.String = "e22bce619ae24ca3b8e6519281cb5a33b64b3190cc763248b4c3f9ad5087a92c";
    val `DA.Random`: _root_.scala.Predef.String = "9de3ae0b7b4e753f7ce2a5dcaa8d49ab4b92c4d8a8fb9589b5f8c893fbea5bd1";
    val `DA.Semigroup.Types`: _root_.scala.Predef.String = "8a7806365bbd98d88b4c13832ebfa305f6abaeaf32cfa2b7dd25c4fa489b79fb";
    val `DA.Set.Types`: _root_.scala.Predef.String = "97b883cd8a2b7f49f90d5d39c981cf6e110cf1f1c64427a28a6d58ec88c43657";
    val `DA.Stack`: _root_.scala.Predef.String = "9de3ae0b7b4e753f7ce2a5dcaa8d49ab4b92c4d8a8fb9589b5f8c893fbea5bd1";
    val `DA.Time.Types`: _root_.scala.Predef.String = "733e38d36a2759688a4b2c4cec69d48e7b55ecc8dedc8067b815926c917a182a";
    val `DA.Types`: _root_.scala.Predef.String = "40f452260bef3f29dede136108fc08a88d5a5250310281067087da6f0baddff7";
    val `DA.Validation.Types`: _root_.scala.Predef.String = "99a2705ed38c1c26cbb8fe7acf36bbf626668e167a33335de932599219e0a235";
    val `GHC.Stack.Types`: _root_.scala.Predef.String = "108aa371793a39379d09dd6f02b5613e8bf37ec9893a826747545df5318475f1";
    val `GHC.Tuple`: _root_.scala.Predef.String = "6839a6d3d430c569b2425e9391717b44ca324b88ba621d597778811b2d05031d";
    val `GHC.Types`: _root_.scala.Predef.String = "518032f41fd0175461b35ae0c9691e08b4aea55e62915f8360af2cc7a1f2ba6c";
    val Topl: _root_.scala.Predef.String = "a605190da006c19e5328416d829a49dfaa2d662a80131bde18212d9db8af7b26"
  }
}
