/*
 * THIS FILE WAS AUTOGENERATED BY THE DIGITAL ASSET Daml SCALA CODE GENERATOR
 * DO NOT EDIT BY HAND!
 */
import _root_.com.daml.ledger.client.{binding=>$u0020lfdomainapi}
import _root_.com.daml.ledger.api.v1.{value=>$u0020rpcvalue}
package co.topl.daml.models {
  package Topl {
    final case class Asset(issuer: ` lfdomainapi`.Primitive.Party, recipient: ` lfdomainapi`.Primitive.Party, nonce: ` lfdomainapi`.Primitive.Text, id: ` lfdomainapi`.Primitive.Text, evidence: ` lfdomainapi`.Primitive.Text, quantity: ` lfdomainapi`.Primitive.Text, assetCode: ` lfdomainapi`.Primitive.Text, metadata: ` lfdomainapi`.Primitive.Text, securityRoot: ` lfdomainapi`.Primitive.Text) extends ` lfdomainapi`.Template[Asset] {
      override protected[this] def templateCompanion(implicit ` d` : ` lfdomainapi`.Compat.DummyImplicit) = Asset
    }

    object Asset extends ` lfdomainapi`.TemplateCompanion[Asset] with _root_.scala.Function9[` lfdomainapi`.Primitive.Party, ` lfdomainapi`.Primitive.Party, ` lfdomainapi`.Primitive.Text, ` lfdomainapi`.Primitive.Text, ` lfdomainapi`.Primitive.Text, ` lfdomainapi`.Primitive.Text, ` lfdomainapi`.Primitive.Text, ` lfdomainapi`.Primitive.Text, ` lfdomainapi`.Primitive.Text, _root_.co.topl.daml.models.Topl.Asset] {
      import _root_.scala.language.higherKinds;
      trait view[` C`[_]] extends ` lfdomainapi`.encoding.RecordView[` C`, view] { $u0020view =>
        val issuer: ` C`[` lfdomainapi`.Primitive.Party];
        val recipient: ` C`[` lfdomainapi`.Primitive.Party];
        val nonce: ` C`[` lfdomainapi`.Primitive.Text];
        val id: ` C`[` lfdomainapi`.Primitive.Text];
        val evidence: ` C`[` lfdomainapi`.Primitive.Text];
        val quantity: ` C`[` lfdomainapi`.Primitive.Text];
        val assetCode: ` C`[` lfdomainapi`.Primitive.Text];
        val metadata: ` C`[` lfdomainapi`.Primitive.Text];
        val securityRoot: ` C`[` lfdomainapi`.Primitive.Text];
        final override def hoist[` D`[_]](` f` : _root_.scalaz.~>[` C`, ` D`]): view[` D`] = {
          final class $anon extends _root_.scala.AnyRef with view[` D`] {
            override val issuer = ` f`(` view`.issuer);
            override val recipient = ` f`(` view`.recipient);
            override val nonce = ` f`(` view`.nonce);
            override val id = ` f`(` view`.id);
            override val evidence = ` f`(` view`.evidence);
            override val quantity = ` f`(` view`.quantity);
            override val assetCode = ` f`(` view`.assetCode);
            override val metadata = ` f`(` view`.metadata);
            override val securityRoot = ` f`(` view`.securityRoot)
          };
          new $anon()
        }
      };
      override val id = ` templateId`(packageId = `Package IDs`.Topl, moduleName = "Topl", entityName = "Asset");
      final implicit class `Asset syntax`[+` ExOn`](private val id: ` ExOn`) extends _root_.scala.AnyVal {
        def exerciseArchive(actor: ` lfdomainapi`.Primitive.Party, choiceArgument: co.topl.daml.models.DA.Internal.Template.Archive)(implicit ` exOn` : ` lfdomainapi`.encoding.ExerciseOn[` ExOn`, Asset]): ` lfdomainapi`.Primitive.Update[` lfdomainapi`.Primitive.Unit] = ` exercise`(actor, id, "Archive", _root_.scala.Some(` lfdomainapi`.Value.encode(choiceArgument)));
        def exerciseArchive(actor: ` lfdomainapi`.Primitive.Party)(implicit ` exOn` : ` lfdomainapi`.encoding.ExerciseOn[` ExOn`, Asset]): ` lfdomainapi`.Primitive.Update[` lfdomainapi`.Primitive.Unit] = exerciseArchive(actor, _root_.co.topl.daml.models.DA.Internal.Template.Archive())
      };
      type key = _root_.scala.Nothing;
      override val consumingChoices: _root_.scala.collection.immutable.Set[` lfdomainapi`.Primitive.ChoiceId] = ` lfdomainapi`.Primitive.ChoiceId.subst(_root_.scala.collection.immutable.Set("Archive"));
      override def toNamedArguments(` self` : Asset) = ` arguments`(scala.Tuple2("issuer", ` lfdomainapi`.Value.encode(` self`.issuer)), scala.Tuple2("recipient", ` lfdomainapi`.Value.encode(` self`.recipient)), scala.Tuple2("nonce", ` lfdomainapi`.Value.encode(` self`.nonce)), scala.Tuple2("id", ` lfdomainapi`.Value.encode(` self`.id)), scala.Tuple2("evidence", ` lfdomainapi`.Value.encode(` self`.evidence)), scala.Tuple2("quantity", ` lfdomainapi`.Value.encode(` self`.quantity)), scala.Tuple2("assetCode", ` lfdomainapi`.Value.encode(` self`.assetCode)), scala.Tuple2("metadata", ` lfdomainapi`.Value.encode(` self`.metadata)), scala.Tuple2("securityRoot", ` lfdomainapi`.Value.encode(` self`.securityRoot)));
      override def fromNamedArguments(` r` : ` rpcvalue`.Record) = if (` r`.fields.length.==(9))
        ` r`.fields(0) match {
          case ` rpcvalue`.RecordField((""| "issuer"), _root_.scala.Some(zv0)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.Party](zv0) match {
            case _root_.scala.Some(z0) => (` r`.fields(1) match {
              case ` rpcvalue`.RecordField((""| "recipient"), _root_.scala.Some(zv1)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.Party](zv1) match {
                case _root_.scala.Some(z1) => (` r`.fields(2) match {
                  case ` rpcvalue`.RecordField((""| "nonce"), _root_.scala.Some(zv2)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.Text](zv2) match {
                    case _root_.scala.Some(z2) => (` r`.fields(3) match {
                      case ` rpcvalue`.RecordField((""| "id"), _root_.scala.Some(zv3)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.Text](zv3) match {
                        case _root_.scala.Some(z3) => (` r`.fields(4) match {
                          case ` rpcvalue`.RecordField((""| "evidence"), _root_.scala.Some(zv4)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.Text](zv4) match {
                            case _root_.scala.Some(z4) => (` r`.fields(5) match {
                              case ` rpcvalue`.RecordField((""| "quantity"), _root_.scala.Some(zv5)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.Text](zv5) match {
                                case _root_.scala.Some(z5) => (` r`.fields(6) match {
                                  case ` rpcvalue`.RecordField((""| "assetCode"), _root_.scala.Some(zv6)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.Text](zv6) match {
                                    case _root_.scala.Some(z6) => (` r`.fields(7) match {
                                      case ` rpcvalue`.RecordField((""| "metadata"), _root_.scala.Some(zv7)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.Text](zv7) match {
                                        case _root_.scala.Some(z7) => (` r`.fields(8) match {
                                          case ` rpcvalue`.RecordField((""| "securityRoot"), _root_.scala.Some(zv8)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.Text](zv8) match {
                                            case _root_.scala.Some(z8) => Some(Asset(z0, z1, z2, z3, z4, z5, z6, z7, z8))
                                            case _root_.scala.None => _root_.scala.None
                                          })
                                          case _ => _root_.scala.None
                                        })
                                        case _root_.scala.None => _root_.scala.None
                                      })
                                      case _ => _root_.scala.None
                                    })
                                    case _root_.scala.None => _root_.scala.None
                                  })
                                  case _ => _root_.scala.None
                                })
                                case _root_.scala.None => _root_.scala.None
                              })
                              case _ => _root_.scala.None
                            })
                            case _root_.scala.None => _root_.scala.None
                          })
                          case _ => _root_.scala.None
                        })
                        case _root_.scala.None => _root_.scala.None
                      })
                      case _ => _root_.scala.None
                    })
                    case _root_.scala.None => _root_.scala.None
                  })
                  case _ => _root_.scala.None
                })
                case _root_.scala.None => _root_.scala.None
              })
              case _ => _root_.scala.None
            })
            case _root_.scala.None => _root_.scala.None
          })
          case _ => _root_.scala.None
        }
      else
        _root_.scala.None;
      override def fieldEncoding(lte: ` lfdomainapi`.encoding.LfTypeEncoding): view[lte.Field] = {
        object `view ` extends view[lte.Field] {
          val issuer = lte.field("issuer", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.Party](lte));
          val recipient = lte.field("recipient", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.Party](lte));
          val nonce = lte.field("nonce", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.Text](lte));
          val id = lte.field("id", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.Text](lte));
          val evidence = lte.field("evidence", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.Text](lte));
          val quantity = lte.field("quantity", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.Text](lte));
          val assetCode = lte.field("assetCode", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.Text](lte));
          val metadata = lte.field("metadata", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.Text](lte));
          val securityRoot = lte.field("securityRoot", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.Text](lte))
        };
        `view `
      };
      override def encoding(lte: ` lfdomainapi`.encoding.LfTypeEncoding)(`view `: view[lte.Field]): lte.Out[_root_.co.topl.daml.models.Topl.Asset] = {
        val `recordFields `: lte.RecordFields[_root_.co.topl.daml.models.Topl.Asset] = lte.RecordFields.xmapN(lte.fields(`view `.issuer), lte.fields(`view `.recipient), lte.fields(`view `.nonce), lte.fields(`view `.id), lte.RecordFields.tupleN(lte.fields(`view `.evidence), lte.fields(`view `.quantity), lte.fields(`view `.assetCode), lte.fields(`view `.metadata), lte.fields(`view `.securityRoot)))({
          case scala.Tuple5(issuer, recipient, nonce, id, scala.Tuple5(evidence, quantity, assetCode, metadata, securityRoot)) => _root_.co.topl.daml.models.Topl.Asset(issuer, recipient, nonce, id, evidence, quantity, assetCode, metadata, securityRoot)
        })({
          case _root_.co.topl.daml.models.Topl.Asset(issuer, recipient, nonce, id, evidence, quantity, assetCode, metadata, securityRoot) => scala.Tuple5(issuer, recipient, nonce, id, scala.Tuple5(evidence, quantity, assetCode, metadata, securityRoot))
        });
        lte.record(` dataTypeId`, `recordFields `)
      }
    }
  }
}
