/*
 * THIS FILE WAS AUTOGENERATED BY THE DIGITAL ASSET Daml SCALA CODE GENERATOR
 * DO NOT EDIT BY HAND!
 */
import _root_.com.daml.ledger.api.v1.{value => $u0020rpcvalue}
import _root_.com.daml.ledger.client.{binding => $u0020lfdomainapi}
package co.topl.daml.driver.models.assets



final case class Asset(issuer: ` lfdomainapi`.Primitive.Party, owner: ` lfdomainapi`.Primitive.Party, assetCode: ` lfdomainapi`.Primitive.Text, quantity: ` lfdomainapi`.Primitive.Int64) extends ` lfdomainapi`.Template[Asset] {
      override protected[this] def templateCompanion(implicit ` d` : ` lfdomainapi`.Compat.DummyImplicit) = Asset
    }

object Asset extends ` lfdomainapi`.TemplateCompanion[Asset] with _root_.scala.Function4[` lfdomainapi`.Primitive.Party, ` lfdomainapi`.Primitive.Party, ` lfdomainapi`.Primitive.Text, ` lfdomainapi`.Primitive.Int64, _root_.com.daml.quickstart.iou.model.DemoAssets.Asset] {
      import _root_.scala.language.higherKinds;
      trait view[` C`[_]] extends ` lfdomainapi`.encoding.RecordView[` C`, view] { $u0020view =>
        val issuer: ` C`[` lfdomainapi`.Primitive.Party];
        val owner: ` C`[` lfdomainapi`.Primitive.Party];
        val assetCode: ` C`[` lfdomainapi`.Primitive.Text];
        val quantity: ` C`[` lfdomainapi`.Primitive.Int64];
        final override def hoist[` D`[_]](` f` : _root_.scalaz.~>[` C`, ` D`]): view[` D`] = {
          final class $anon extends _root_.scala.AnyRef with view[` D`] {
            override val issuer = ` f`(` view`.issuer);
            override val owner = ` f`(` view`.owner);
            override val assetCode = ` f`(` view`.assetCode);
            override val quantity = ` f`(` view`.quantity)
          };
          new $anon()
        }
      };
      override val id = ` templateId`(packageId = `Package IDs`.DemoAssets, moduleName = "DemoAssets", entityName = "Asset");
      final implicit class `Asset syntax`[+` ExOn`](private val id: ` ExOn`) extends _root_.scala.AnyVal {
        def exerciseArchive(actor: ` lfdomainapi`.Primitive.Party, choiceArgument: com.daml.quickstart.iou.model.DA.Internal.Template.Archive)(implicit ` exOn` : ` lfdomainapi`.encoding.ExerciseOn[` ExOn`, Asset]): ` lfdomainapi`.Primitive.Update[` lfdomainapi`.Primitive.Unit] = ` exercise`(actor, id, "Archive", _root_.scala.Some(` lfdomainapi`.Value.encode(choiceArgument)));
        def exerciseArchive(actor: ` lfdomainapi`.Primitive.Party)(implicit ` exOn` : ` lfdomainapi`.encoding.ExerciseOn[` ExOn`, Asset]): ` lfdomainapi`.Primitive.Update[` lfdomainapi`.Primitive.Unit] = exerciseArchive(actor, _root_.com.daml.quickstart.iou.model.DA.Internal.Template.Archive())
      };
      type key = _root_.scala.Nothing;
      override val consumingChoices: _root_.scala.collection.immutable.Set[` lfdomainapi`.Primitive.ChoiceId] = ` lfdomainapi`.Primitive.ChoiceId.subst(_root_.scala.collection.immutable.Set("Archive"));
      override def toNamedArguments(` self` : Asset) = ` arguments`(scala.Tuple2("issuer", ` lfdomainapi`.Value.encode(` self`.issuer)), scala.Tuple2("owner", ` lfdomainapi`.Value.encode(` self`.owner)), scala.Tuple2("assetCode", ` lfdomainapi`.Value.encode(` self`.assetCode)), scala.Tuple2("quantity", ` lfdomainapi`.Value.encode(` self`.quantity)));
      override def fromNamedArguments(` r` : ` rpcvalue`.Record) = if (` r`.fields.length.==(4))
        ` r`.fields(0) match {
          case ` rpcvalue`.RecordField((""| "issuer"), _root_.scala.Some(zv0)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.Party](zv0) match {
            case _root_.scala.Some(z0) => (` r`.fields(1) match {
              case ` rpcvalue`.RecordField((""| "owner"), _root_.scala.Some(zv1)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.Party](zv1) match {
                case _root_.scala.Some(z1) => (` r`.fields(2) match {
                  case ` rpcvalue`.RecordField((""| "assetCode"), _root_.scala.Some(zv2)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.Text](zv2) match {
                    case _root_.scala.Some(z2) => (` r`.fields(3) match {
                      case ` rpcvalue`.RecordField((""| "quantity"), _root_.scala.Some(zv3)) => (` lfdomainapi`.Value.decode[` lfdomainapi`.Primitive.Int64](zv3) match {
                        case _root_.scala.Some(z3) => Some(Asset(z0, z1, z2, z3))
                        case _root_.scala.None => _root_.scala.None
                      })
                      case _ => _root_.scala.None
                    })
                    case _root_.scala.None => _root_.scala.None
                  })
                  case _ => _root_.scala.None
                })
                case _root_.scala.None => _root_.scala.None
              })
              case _ => _root_.scala.None
            })
            case _root_.scala.None => _root_.scala.None
          })
          case _ => _root_.scala.None
        }
      else
        _root_.scala.None;
      override def fieldEncoding(lte: ` lfdomainapi`.encoding.LfTypeEncoding): view[lte.Field] = {
        object `view ` extends view[lte.Field] {
          val issuer = lte.field("issuer", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.Party](lte));
          val owner = lte.field("owner", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.Party](lte));
          val assetCode = lte.field("assetCode", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.Text](lte));
          val quantity = lte.field("quantity", ` lfdomainapi`.encoding.LfEncodable.encoding[` lfdomainapi`.Primitive.Int64](lte))
        };
        `view `
      };
      override def encoding(lte: ` lfdomainapi`.encoding.LfTypeEncoding)(`view `: view[lte.Field]): lte.Out[_root_.com.daml.quickstart.iou.model.DemoAssets.Asset] = {
        val `recordFields `: lte.RecordFields[_root_.com.daml.quickstart.iou.model.DemoAssets.Asset] = lte.RecordFields.xmapN(lte.fields(`view `.issuer), lte.fields(`view `.owner), lte.fields(`view `.assetCode), lte.fields(`view `.quantity))({
          case scala.Tuple4(issuer, owner, assetCode, quantity) => _root_.com.daml.quickstart.iou.model.DemoAssets.Asset(issuer, owner, assetCode, quantity)
        })({
          case _root_.com.daml.quickstart.iou.model.DemoAssets.Asset(issuer, owner, assetCode, quantity) => scala.Tuple4(issuer, owner, assetCode, quantity)
        });
        lte.record(` dataTypeId`, `recordFields `)
      }
    }
